# Afterglow — Alacritty Color Scheme

[colors.primary]
background = "#F4EEE1"
foreground = "#24163B"

[colors.cursor]
text = "#F4EEE1"
cursor = "#C3228E"

[colors.selection]
text = "#F4EEE1"
background = "#DFC2AA"

[colors.normal]
black = "#24163B"
red = "#B12531"
green = "#22775B"
yellow = "#A25410"
blue = "#1D7187"
magenta = "#8930A6"
cyan = "#AE296B"
white = "#574979"

[colors.bright]
black = "#CDAEA2"
red = "#B12531"
green = "#22775B"
yellow = "#A25410"
blue = "#1D7187"
magenta = "#8930A6"
cyan = "#AE296B"
white = "#24163B"
